"""
This type stub file was generated by pyright.
"""

import importlib
from typing import Any
from . import types, version
from .client import Client

"""Google Gen AI SDK"""
__version__ = ...
__all__ = ['Client', 'credentials', 'interactions', 'types']
def __getattr__(name: str) -> Any:
  ...

